### PR TITLE
Fixes drop on wire issues

### PR DESCRIPTION
**Pull request by j8sr0230**
The Pyflow documentation describes the drop on wire functionality. However, this does not work in the current version. This commit fixes the problem by making additions to the mouseReleaseEvent of the BlueprintCanvas class.

### CODE REVIEW

**Comment by luzpaz** [comment]
@AbdelazizSharaf001 do you mind reviewing this PR ?

**Comment by j8sr0230** [comment]
I noticed this morning that it's actually not a fix, but a new feature. My code adds the functionality Drop on Wire from nodes that are already on the canvas and are dragged onto a wire. In the video documentation Drop On Wire is shown from the nodebox onto a wire, which unfortunately does not work either. For this I have coded an actual fix (see my fork). In my fork, Drop on Wire works out of Canvas and out of Nodebox. In addition, there is now also Drop On Pin, which you can not see at all in the video documentation :)
@AbdelazizSharaf001 If requested, I will be happy to create a pull request with the mentioned additions.

**Comment by j8sr0230** [comment]
In my fork of AnimationFreeCAD to be precise: [https://github.com/j8sr0230/AnimationFreeCAD](url). Just let me know if you want me to put it in the PyFlow upstream.

**Comment by Sharaf5** [comment]
Seems you are better than me @j8sr0230
I tested the drop on wire fix for standalone, and it works out of the box
But I should note that you are using hard coded path for macro dir, we need it to run on every platform so this should be able to change depending on the os type
Thanks for adjusting btn order, I was going modify it and add a merge request, but I see you did here

**Comment by j8sr0230** [comment]
Interesting, actually I only wanted to make a pull request regarding the drop on wire functionality. All other commits I did in my own fork of PyFlow. I didn't know that all commits are sent upstream. Is there any way to prevent this so that I only push my changes into my fork initially?

**Comment by j8sr0230** [comment]
@AbdelazizSharaf001 Thanks for rating. I have done some more research. As long as a pull request is open, all further commits in my fork are automatically merged. Of course, that was not my intention. The clean solution is to create a separate branch for each pull to control exactly what should be merged. For this reason, I am closing this pull and continuing to work in my own fork until I have enough input for a meaningful pull request.

**Pull request closed without merging**
