### PR TITLE
compatibility fix

### PR DESCRIPTION
**Pull request by microelly2**
two problems running on linux python 2

### CODE REVIEW

**Comment by looooo** [comment]
@microelly2 Looks like a lot of diff. Can you explain the problems you were running into?

**Comment by luzpaz** [comment]
@microelly2 are you still working on this PR ?

**Comment by IlgarLunin** [comment]
I believe it is outdated

**Comment by microelly2** [comment]
We can delete the request,
I work with python3 and have  a modified version which is still compatible/mergable with the main stream.

**Pull request closed without merging**
